Update code execution language
csesoc/discord-bot pull request #62
Opened 2022-08-19 06:45 UTC by Oscaz

Move the language to lowercase to remove case sensitivity.
See list of runtimes here: https://emkc.org/api/v2/piston/runtimes
All of which are in lowercase.

2022-11-04 11:43 UTC, zaxutic approved these changes
lgtm

2022-11-04 11:44 UTC, rizmanter11 requested changes
I will not allow this to be merged

2022-11-04 11:55 UTC, imagine-hussain commented
lgtm 👍

2022-11-04 11:55 UTC, imagine-hussain approved these changes

2022-11-04 11:55 UTC, imagine-hussain commented
okay but fr, can we merge this

2022-11-04 11:57 UTC, rizmanter11 reviewed
I am still not 100% sure we are supposed to have the code feature. Apparently execs wanted it gone.

2022-11-05 03:58 UTC, Oscaz commented
![Untitled4](https://user-images.githubusercontent.com/19832216/200099769-d771712a-20e5-41e2-a22d-3fb43bb37818.png)

2022-11-06 02:30 UTC, imagine-hussain commented
> I am still not 100% sure we are supposed to have the code feature. Apparently execs wanted it gone.

well, we'll remove it when the time comes but for now it's still active and so might as well merge in fixes

2022-11-06 02:31 UTC, rizmanter11 commented
> 

Ok you've convinced me

2022-11-06 02:32 UTC, merged